<a href="https://colab.research.google.com/github/djammy/DeepLearning-with-PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have any questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions



In [ ]:
print("Hello I am excited to learn about PyTorch from Daniel Bourke")

Hello I am excited to learn about PyTorch from Daniel Bourke


In [ ]:
!nvidia-smi

Wed Aug  3 16:41:26 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
import pandas as pandas
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

1.12.0+cu113


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim
# dimension will return 0 as a scalar has none

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]], [[3, 23, 35],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[ 3, 23, 35],
         [ 3,  6,  9],
         [ 2,  4,  5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1]

tensor([[ 3, 23, 35],
        [ 3,  6,  9],
        [ 2,  4,  5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they strt with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors documentation: https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of shape/size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4631, 0.4446, 0.7104, 0.9545],
        [0.4309, 0.8993, 0.7363, 0.3248],
        [0.6308, 0.8548, 0.1023, 0.7411]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

## Why would need a zeroes tensor?

### Simple to act as a mask. For instance, you want to mask out say all of the numbers in all of the column, and multiply by target tensor

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

##Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arange()

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeroes = torch.ones_like(input=one_to_ten)
ten_zeroes

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

##Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# FLoat 32 tensor (default data type)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype = None, # what datatype is the tensor (e.g. float32 or float16)
                               device = None, # what device is your tensor on
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3382, 0.7660, 0.6782, 0.5120],
        [0.8902, 0.4395, 0.6127, 0.4556],
        [0.7413, 0.1798, 0.9282, 0.2641]])

In [ ]:
from torch._C import device
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3382, 0.7660, 0.6782, 0.5120],
        [0.8902, 0.4395, 0.6127, 0.4556],
        [0.7413, 0.1798, 0.9282, 0.2641]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (eement-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it

tensor = torch.tensor([1, 2, 3])
tensor +  10

tensor([11, 12, 13])

In [ ]:
#  Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix  Mutiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise  multiplication
2. Matrix multiplication (or referred to as dot product)

There are two main rules that performing matrix multiplication need to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` will not work
* `(2, 3) @ (3, 2)` will work
*                                                                                                          

In [ ]:
# Element-wise multiplication
print(tensor, "*", tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [ ]:
print(f"Equals: {tensor * tensor}")

Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 324 µs, sys: 66 µs, total: 390 µs
Wall time: 1.02 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 32 µs, sys: 0 ns, total: 32 µs
Wall time: 36 µs


tensor(14)

In [ ]:
A = torch.randn(3, 2, 3)

In [ ]:
A

tensor([[[ 1.0111,  1.0229, -1.1183],
         [ 1.4124,  1.9706, -0.0023]],

        [[-0.1003, -0.9356, -0.5792],
         [-1.6388, -0.7023,  0.9719]],

        [[ 0.2448, -1.5368, -0.4829],
         [-0.3279,  0.4851,  1.1363]]])

In [ ]:
tensor_A = torch.rand(2,5)
tensor_B = torch.rand(2,5)
tensor_A, tensor_B

(tensor([[0.4121, 0.9581, 0.3046, 0.5759, 0.3969],
         [0.1260, 0.4445, 0.9772, 0.8586, 0.5495]]),
 tensor([[0.9886, 0.2538, 0.5436, 0.7274, 0.1491],
         [0.2510, 0.4169, 0.5860, 0.8467, 0.8194]]))

In [ ]:
tensor_A

tensor([[0.4121, 0.9581, 0.3046, 0.5759, 0.3969],
        [0.1260, 0.4445, 0.9772, 0.8586, 0.5495]])

In [ ]:
tensor_B

tensor([[0.9886, 0.2538, 0.5436, 0.7274, 0.1491],
        [0.2510, 0.4169, 0.5860, 0.8467, 0.8194]])

In [ ]:
tensor_A * tensor_B

tensor([[0.4074, 0.2432, 0.1655, 0.4189, 0.0592],
        [0.0316, 0.1853, 0.5726, 0.7270, 0.4502]])

In [ ]:
torch.mm(tensor_A,tensor_B.T)

tensor([[1.2942, 1.4941],
        [1.4751, 1.9667]])

## Finding the min max, mean, sum, etc (Tensor aggregation)

It is called aggregation because you are typically going from a large amount of numbers to a single value

In [ ]:
# Cc=reate a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean (should either be a floating point or complex)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()


(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[x.argmax()]

tensor(90)

##Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tesnor of certains shape but keep the same memory as the original tensor
* Stacking - comibine multiple tensors on top of each other or side by side
* Squeeze - removes all `1` dimensions from tensorboard* Unsqueeze - add `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# Create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x.ndim, x_reshaped.ndim

(1, 2)

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5 # changing the first element of z to 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single diemsnion to a target tensor at a specific dimension
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
xx = torch.zeros(2, 1, 2, 1, 2)
xx, xx.ndim

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]), 5)

In [ ]:
xxx = xx.squeeze()
xxx

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
xxx.unsqueeze(dim=3).shape

torch.Size([2, 2, 2, 1])

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
x_original, x_original.shape


(tensor([[[0.1684, 0.4639, 0.3856],
          [0.5997, 0.1251, 0.2861],
          [0.6163, 0.5679, 0.2564],
          ...,
          [0.4658, 0.1051, 0.2601],
          [0.1065, 0.8471, 0.5795],
          [0.6349, 0.9229, 0.5704]],
 
         [[0.1172, 0.4647, 0.0196],
          [0.1911, 0.4228, 0.2172],
          [0.4384, 0.6409, 0.9869],
          ...,
          [0.9124, 0.8003, 0.7914],
          [0.2026, 0.6580, 0.9944],
          [0.0213, 0.3366, 0.8086]],
 
         [[0.4400, 0.4482, 0.2385],
          [0.9332, 0.1719, 0.4054],
          [0.9624, 0.4614, 0.1544],
          ...,
          [0.8145, 0.1562, 0.2508],
          [0.9315, 0.1652, 0.0702],
          [0.3452, 0.3053, 0.2573]],
 
         ...,
 
         [[0.2217, 0.5856, 0.6373],
          [0.4468, 0.6825, 0.8021],
          [0.5422, 0.6960, 0.4945],
          ...,
          [0.4202, 0.1552, 0.1267],
          [0.8106, 0.5517, 0.0273],
          [0.7203, 0.8763, 0.5546]],
 
         [[0.1827, 0.7532, 0.6638],
          [0

In [ ]:
# Permute the originl tensor to rearrange the axis (or dim)  order
x_permuted = x_original.permute(2,0,1)
x_permuted, x_permuted.shape

(tensor([[[0.1684, 0.5997, 0.6163,  ..., 0.4658, 0.1065, 0.6349],
          [0.1172, 0.1911, 0.4384,  ..., 0.9124, 0.2026, 0.0213],
          [0.4400, 0.9332, 0.9624,  ..., 0.8145, 0.9315, 0.3452],
          ...,
          [0.2217, 0.4468, 0.5422,  ..., 0.4202, 0.8106, 0.7203],
          [0.1827, 0.2407, 0.6949,  ..., 0.4450, 0.4661, 0.5893],
          [0.4761, 0.7265, 0.6789,  ..., 0.9991, 0.0644, 0.0180]],
 
         [[0.4639, 0.1251, 0.5679,  ..., 0.1051, 0.8471, 0.9229],
          [0.4647, 0.4228, 0.6409,  ..., 0.8003, 0.6580, 0.3366],
          [0.4482, 0.1719, 0.4614,  ..., 0.1562, 0.1652, 0.3053],
          ...,
          [0.5856, 0.6825, 0.6960,  ..., 0.1552, 0.5517, 0.8763],
          [0.7532, 0.5680, 0.3610,  ..., 0.2896, 0.8920, 0.8588],
          [0.6743, 0.9329, 0.0056,  ..., 0.5546, 0.9628, 0.4761]],
 
         [[0.3856, 0.2861, 0.2564,  ..., 0.2601, 0.5795, 0.5704],
          [0.0196, 0.2172, 0.9869,  ..., 0.7914, 0.9944, 0.8086],
          [0.2385, 0.4054, 0.1544,  ...,

In [ ]:
print(f'Previous shape: {x_original.shape}') # [heigth, width, colour_channels]
print(f'New shape: {x_permuted.shape}') # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
# Indexing

x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[0,:,2]


tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor (you want to leverage PyTorch capability to study your data which is in NumPy format/array) -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`


In [ ]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy to pytorch, pytorch reflects numpy data type of float 64 unless specified otherwise
tensor_32 = torch.from_numpy(array).type(torch.float32)
array, tensor, tensor_32, tensor_32.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
array.dtype

dtype('float64')

In [ ]:
#  Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to `numpy` tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Rproducibility (Trying to take the random out of random)

In short, how a neural network learns:

`start with random numbers -> perform tensor operations -> update random numbers to try and make them better representation of the data -> again -> again -> again...`

To reduce the randomness in ne ural netowkrs, and PyTorch comes the concept of a **random seed**.

Essentially, what the random seed does is flavour the randomness.

In [ ]:
torch.rand(3, 3) # if you run this line of code multiple times, you will get different outcomes each time, and this isn't good if you are trying to reproduce your results

tensor([[0.7838, 0.7124, 0.4172],
        [0.0493, 0.3612, 0.1482],
        [0.9690, 0.3730, 0.2506]])

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B) # Boolean to see if True or False

tensor([[0.7654, 0.5333, 0.8078, 0.9637],
        [0.8233, 0.1175, 0.7235, 0.6252],
        [0.0732, 0.3920, 0.1408, 0.7859]])
tensor([[0.3459, 0.8507, 0.6712, 0.7945],
        [0.8896, 0.5622, 0.9921, 0.3808],
        [0.6992, 0.5014, 0.1533, 0.5033]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers thanks to CUDA + NVIDIA hardware + PyTorch working bhind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU 
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP (Google Cloud Platform), AWS (Amazon Web Service), Azure (Microsoft)

In [ ]:
!nvidia-smi

Wed Aug  3 16:41:31 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU acces with PyTorch

In [ ]:
# Check for GPU access with PyTorch

torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# Count the number of GPUs/devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (Default on the cpu)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum